#!/bin/bash

#SBATCH --partition debug
#SBATCH --ntasks 4
#SBATCH --output /dev/null
#SBATCH --error error
#SBATCH --time 00:10:00
#SBATCH --job-name TrilinosConfigure
#SBATCH --mail-user your_username@unm.edu
#SBATCH --mail-type ALL

bash load
cd ../build 
srun make -j 4
srun make test
