#!/bin/bash

#SBATCH --partition debug
#SBATCH --ntasks 1
#SBATCH --output /dev/null
#SBATCH --error error
#SBATCH --time 00:15:00
#SBATCH --job-name TrilinosConfigure
#SBATCH --mail-user your_username@unm.edu
#SBATCH --mail-type ALL

