#!/bin/bash

#SBATCH --partition debug
#SBATCH --ntasks 1
#SBATCH --mem 8G
#SBATCH --output output.txt
#SBATCH --error error
#SBATCH --time 00:20:00
#SBATCH --job-name TrilinosTest
#SBATCH --mail-user your_username@unm.edu
#SBATCH --mail-type ALL
